#!/bin/bash 
set -euo pipefail

source ./server-config.sh

main() {
  build_image
  echo "Starting onboarding framework container..."
  start_container
  docker logs $ONBOARD_DEMO_CONTAINER -f
}

build_image() {
  cd build
    ./build.sh
  cd .. 
}

start_container() {
    docker run -d			\
    --name $ONBOARD_DEMO_CONTAINER	\
    -e "TERM=xterm"			\
    --restart always			\
    --entrypoint "sh" 			\
    -v $(pwd):/home/demo		\
    -p "$ONBOARD_PORT:8000"		\
    $ONBOARD_DEMO_IMAGE			\
    -c "export PYTHONPATH=\$PYTHONPATH:./lib; uvicorn onboard-main:app --reload --host 0.0.0.0"
}

main $@
